-- Update users table with all required fields
ALTER TABLE users
ADD COLUMN IF NOT EXISTS first_name VARCHAR(50) NOT NULL,
ADD COLUMN IF NOT EXISTS last_name VARCHAR(50) NOT NULL,
ADD COLUMN IF NOT EXISTS email VARCHAR(100) NOT NULL UNIQUE,
ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS role ENUM('student', 'admin', 'teacher') NOT NULL DEFAULT 'student',
ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(100),
ADD COLUMN IF NOT EXISTS student_id VARCHAR(20) UNIQUE,
ADD COLUMN IF NOT EXISTS year INT,
ADD COLUMN IF NOT EXISTS semester INT,
ADD COLUMN IF NOT EXISTS department VARCHAR(50),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add constraints
ALTER TABLE users
ADD CONSTRAINT check_year CHECK (year BETWEEN 1 AND 5),
ADD CONSTRAINT check_semester CHECK (semester BETWEEN 1 AND 2);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_student_id ON users(student_id);
CREATE INDEX IF NOT EXISTS idx_department ON users(department);
CREATE INDEX IF NOT EXISTS idx_role ON users(role); 